---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloud-native-cap-hdi-container
data:
  # fill secret key from CF runtime, each field should encode with base64
  url: ""
  driver: ""
  hdi_password: ""
  hdi_user: ""
  host: ""
  password: ""
  port: ""
  schema: ""
  user: ""
  certificate: ""
